version: '3.8'

services:

  client:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./app:/app
    tty: true
    stdin_open: true